### ISSUE TITLE
GKE - Error loading CAPS in ds.yaml

### ISSUE THREAD

**Issue by tisc0** [Xide/kube2allow#2]
Hi,

Here is a little error easily fixed : 
``` 
 Warning  Failed     7m16s (x5 over 8m48s)  kubelet, gke-idp-datastore-cluster-main-pool-ae153987-qw1p  Error: failed to start container "kube2allow-auditor": Error response from daemon: linux spec capabilities: Unknown capability to add: "CAP_CAP_SYS_PTRACE"
```

With this (ds.yaml) : 
```
(...)
        securityContext:
          runAsUser: 0
          capabilities:
            add:
            - SYS_PTRACE
            - SYS_ADMIN
```
But since I know you've tested it before pushing, might it be a specificity of GKE ?

Thanks again !
